grpc:
  host: "0.0.0.0"
  port: 5001
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8080

log:
  level: debug
  file_path: ./logs/identity-mservice.log

system:
  allowed_origins: 
  - https://campaign-center-admin-web.vercel.app
  - https://finverse-web.vercel.app
  - http://localhost:3000

singpass:
  redirect_uri: "http://localhost:8080/identity-ms/v1/kyc/singpass/callback"
  scope: "openid name email uinfin mobileno"
  issuer_url: "https://campaignhub.best/mockpass/singpass/v2"
  token_url: "https://campaignhub.best/mockpass/singpass/v2/token"
  user_info_url: "https://campaignhub.best/mockpass/singpass/v2/userinfo"
  jwks_uri: "https://campaignhub.best/mockpass/singpass/v2/.well-known/keys"
