// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/identity-ms/v1/clerk/callback": {
            "post": {
                "description": "Verifies Svix signature headers and accepts Clerk webhook events (e.g. user.created).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clerk-webhook"
                ],
                "summary": "Clerk webhook callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Svix message ID",
                        "name": "svix-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Svix HMAC signature",
                        "name": "svix-signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unix timestamp of the webhook message",
                        "name": "svix-timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Raw Clerk webhook event JSON payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "webhook accepted"
                    },
                    "400": {
                        "description": "missing svix headers, invalid body, or invalid signature",
                        "schema": {
                            "$ref": "#/definitions/api.ClerkCallbackErrorResponse"
                        }
                    },
                    "500": {
                        "description": "webhook verification init failed",
                        "schema": {
                            "$ref": "#/definitions/api.ClerkCallbackErrorResponse"
                        }
                    }
                }
            }
        },
        "/identity-ms/v1/web/user-profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-profile"
                ],
                "summary": "Get user profile (user)",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/api.UserProfileHTTPResponse"
                        }
                    },
                    "404": {
                        "description": "user not found",
                        "schema": {
                            "$ref": "#/definitions/data.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/data.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ClerkCallbackErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Missing svix headers"
                }
            }
        },
        "api.UserProfileData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "a***e@example.com"
                },
                "kycChecked": {
                    "type": "boolean",
                    "example": true
                },
                "registeredAt": {
                    "type": "string",
                    "example": "2026-05-16T10:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "api.UserProfileHTTPResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/api.UserProfileData"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "data.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "err_msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
