definitions:
  api.UserProfileData:
    properties:
      email:
        example: a***e@example.com
        type: string
      kycChecked:
        example: true
        type: boolean
      registeredAt:
        example: "2026-05-16T10:00:00Z"
        type: string
      username:
        example: alice
        type: string
    type: object
  api.UserProfileHTTPResponse:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/api.UserProfileData'
      message:
        example: success
        type: string
    type: object
  data.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      err_msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /identity-ms/v1/web/user-profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/api.UserProfileHTTPResponse'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Get user profile (user)
      tags:
      - user-profile
swagger: "2.0"
