// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/identity-mservice/server/repository/model"
)

// UserAuthMappingDao is an autogenerated mock type for the UserAuthMappingDao type
type UserAuthMappingDao struct {
	mock.Mock
}

// CreateInTransaction provides a mock function with given fields: trx, userAuthMapping
func (_m *UserAuthMappingDao) CreateInTransaction(trx *gorm.DB, userAuthMapping *model.UserAuthMapping) error {
	ret := _m.Called(trx, userAuthMapping)

	if len(ret) == 0 {
		panic("no return value specified for CreateInTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.UserAuthMapping) error); ok {
		r0 = rf(trx, userAuthMapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByClerkUserID provides a mock function with given fields: ctx, clerkUserID
func (_m *UserAuthMappingDao) GetByClerkUserID(ctx context.Context, clerkUserID string) (*model.UserAuthMapping, error) {
	ret := _m.Called(ctx, clerkUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClerkUserID")
	}

	var r0 *model.UserAuthMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserAuthMapping, error)); ok {
		return rf(ctx, clerkUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserAuthMapping); ok {
		r0 = rf(ctx, clerkUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAuthMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clerkUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserAuthMappingDao) GetByEmail(ctx context.Context, email string) (*model.UserAuthMapping, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *model.UserAuthMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserAuthMapping, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserAuthMapping); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAuthMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserAuthMappingDao creates a new instance of UserAuthMappingDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAuthMappingDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAuthMappingDao {
	mock := &UserAuthMappingDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
