// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/identity-mservice/server/repository/model"
)

// UserDao is an autogenerated mock type for the UserDao type
type UserDao struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserDao) GetByID(ctx context.Context, id int64) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserDao creates a new instance of UserDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDao {
	mockUserDao := &UserDao{}
	mockUserDao.Mock.Test(t)

	t.Cleanup(func() { mockUserDao.AssertExpectations(t) })

	return mockUserDao
}
